name: Run Automation Tests

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow on. Adjust if needed.

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pulls the latest code from your repository.

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin distribution.
          java-version: '21'       # Specify your Java version (e.g., 8, 11, 17).

      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Run Tests
        run: mvn clean test